export const mockProducts = [
  { "id": 0, "name": "Fantastic Chicken","price": 83 },
  { "id": 1, "name": "Handmade Chair", "price": 197 },
  { "id": 2, "name": "Rustic Hat", "price": 351 },
  { "id": 3, "name": "Generic Chips", "price": 630},
  { "id": 4, "name": "Ergonomic Chicken", "price": 80 },
  { "id": 5, "name": "Generic Soap", "price": 637 },
  { "id": 6, "name": "Handcrafted Car", "price": 95 },
  { "id": 7, "name": "Gorgeous Cheese", "price": 583 },
  { "id": 8, "name": "Gorgeous Shoes", "price": 100 },
  { "id": 9, "name": "Generic Gloves", "price": 542 },
  { "id": 10, "name": "Tasty Soap", "price": 668 },
  { "id": 11, "name": "Rustic Sausages", "price": 931 },
  { "id": 12, "name": "Awesome Bacon", "price": 331 },
  { "id": 13, "name": "Tasty Pizza", "price": 903 },
  { "id": 14, "name": "Handmade Sausages", "price": 28 },
  { "id": 15, "name": "Fantastic Soap", "price": 190 },
  { "id": 16, "name": "Intelligent Chips", "price": 277 },
  { "id": 17, "name": "Rustic Hat", "price": 518 },
  { "id": 18, "name": "Licensed Hat", "price": 165 },
  { "id": 19, "name": "Fantastic Chips", "price": 573 },
  { "id": 20, "name": "Unbranded Chips", "price": 495 },
  { "id": 21, "name": "Practical Soap", "price": 592},
  { "id": 22, "name": "Tasty Sausages", "price": 266 },
  { "id": 23, "name": "Rustic Mouse", "price": 76 },
  { "id": 24, "name": "Ergonomic Bacon", "price": 636 },
  { "id": 25, "name": "Licensed Mouse", "price": 695 },
  { "id": 26, "name": "Small Computer", "price": 838 },
];